### ISSUE TITLE
Use the file to convert the original ANHIR dataset into the format used by the DeepHistReg framework.

### ISSUE THREAD

**Issue by TIEHua** [MWod/DeepHistReg#1]
I don't know how to convert? The original image is '.jpg' or 'png' but in your code, it's 'mha' in the parse_dataset.py.
Did you convert all the images into 'mha' at first? I don't find any code to complete this process in the file.

**Comment by MWod** [comment]
The [prepare_datasets.py](https://github.com/lNefarin/DeepHistReg/blob/master/prepare_datasets.py) file parses the input .jpg/.png files to the .mha format. You may also choose the output resolution (the higher resolution, the longer the training time and the more accurate the registration).

**Comment by TIEHua** [comment]
The code line 38 and 39 in prepare_datasets.py 
**_source_path = os.path.join(dataset_path, source_path.replace(extension, ".mha"))
target_path = os.path.join(dataset_path, target_path.replace(extension, ".mha"))_**
I think it should be
"
source_path = os.path.join(dataset_path, source_path)
target_path = os.path.join(dataset_path, target_path)
"
The original data has no 'mha' file.

**Comment by MWod** [comment]
Please find new file [parse_to_mha.py](https://github.com/lNefarin/DeepHistReg/blob/master/parse_to_mha.py) to parse the original ANHIR data to the .mha format.

**Comment by TIEHua** [comment]
Thanks a lot!
