### ISSUE TITLE
Is it feasible to modify the code for 2D affine registration to 3D

### ISSUE THREAD

**Issue by mtcluo** [MWod/DeepHistReg#4]
I'm the beginner of the learning based registration. Do you think it's feasible to directly modify your code for 2D affine registration to 3D？

**Comment by MWod** [comment]
It should be rather straightforward. Anyway, I plan to release the code for 3-D affine/nonrigid registration in January/February (in a separate repository) dedicated to the breast tumor bed localization (CT-CT or CT-MRI registration).

**Comment by mtcluo** [comment]
Could you send the code about 3-D affine/nonrigid registration to me? I tried to modify the 2-D affine code, but it didn't work. 
Hope you could help me.  Thank you very much!!

**Comment by YMBrianHung** [comment]
> It should be rather straightforward. Anyway, I plan to release the code for 3-D affine/nonrigid registration in January/February (in a separate repository) dedicated to the breast tumor bed localization (CT-CT or CT-MRI registration).

Will the 3-D affine registration network work on the brian registration?

**Comment by MWod** [comment]
I will create another repository with the 3-D registration code when it will be ready, hopefully soon.
