### ISSUE TITLE
Does the affine registation network work on the brian registation?

### ISSUE THREAD

**Issue by YMBrianHung** [MWod/DeepHistReg#5]
1

**Comment by MWod** [comment]
It depends what exactly you want to achieve. Generally, modifying the network from 2-D to 3-D should be rather straightforward, (just change the layers from 2-D to 3-D) however, for 3-D brain registration you probably need to use different similarity measure (e.g. NCC will not work for the registration of T1W images to T2W images).
Yes, I am currently working on DL-based 3-D registration and will publish the repository when ready.

**Comment by YMBrianHung** [comment]
My study is to register two brain volumes from two different subject (a moving volume to an atlas).   Does NCC work for this registration?

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: lNefarin<mailto:notifications@github.com>
发送时间: 2021年1月25日 18:05
收件人: lNefarin/DeepHistReg<mailto:DeepHistReg@noreply.github.com>
抄送: YMBrianHung<mailto:brianhung24@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [lNefarin/DeepHistReg] Does the affine registation network work on the brian registation? (#5)


It depends what exactly you want to achieve. Generally, modifying the network from 2-D to 3-D should be rather straightforward, (just change the layers from 2-D to 3-D) however, for 3-D brain registration you probably need to use different similarity measure (e.g. NCC will not work for the registration of T1W images to T2W images).
Yes, I am currently working on DL-based 3-D registration and will publish the repository when ready.

―

**Comment by MWod** [comment]
As mentioned, all depends on the dataset. I suggest you to read e.g. https://arxiv.org/pdf/1903.08811.pdf where a good learning-based approach for the affine registration is discussed. If the only thing you want to achieve is the affine registration - there are numerous works about the affine registration of brain together with open implementations.
